---
apiVersion: v1
kind: Service
metadata:
  name: sdc-dnninference-half-service
  namespace: sdc-dnninference
spec:
  selector:
    app: sdc-dnninference-half-app-label
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30103
---
apiVersion: apps/v1                          
kind: ReplicaSet                               
metadata:
  name: sdc-dnninference-half-replicaset
  namespace: sdc-dnninference
  labels:                               
    app: sdc-dnninference-half-app-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sdc-dnninference-half-app-label
  template:
    metadata:
      name: sdc-dnninference-half-ReplicaSet
      labels:
        app: sdc-dnninference-half-app-label
    spec:
      nodeName: tank-node2                 # node name
      containers:
      - name: sdc-dnninference-half-con      
        image: sdcbench/dnninference-tfserving:2.3.0   
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
        - name: MODEL_NAME
          value: "half"
        volumeMounts:
        - name: model-path
          mountPath: /models/half
      volumes:
      - name: model-path
        hostPath:
          path: /mnt/sdcbench/dnninference/models/half
